### ISSUE TITLE
can't be reactivated after page reload on Chrome

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#104]
@monzug reports that with the issue-inflections-59 build after page reload it's no longer possible to activate Alpheios in Chrome. It still works fine in Firefox.

I suspect this might have been introduced by #102 

Assigning to @irina060981 to investigate.

**Comment by irina060981** [comment]
@balmas, I have made an investigation and find out that when Chrome returns callback for `browser.webNavigation.onCompleted` it doen't have windowId, so the page couldn't be correctly reloaded (and it is not correctly unloaded because it has previously loaded content)

As for Firefox - it has windowId in a callback for `browser.webNavigation.onCompleted`

**Comment by irina060981** [comment]
I suggest such a variant
https://github.com/alpheios-project/webextension/pull/108

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
thanks. I can't wait to see this been fixed

**Comment by balmas** [comment]
@monzug this can now be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
it works on firefox and chrome, except for the text.html (the Multilanguage file provided by Bridget). in both browser, after reloading the page the extension is on but does not work (no double-clicking, no panel on). if I reload the page, the extension does not activate at all.

**Comment by irina060981** [comment]
@monzug, Monica, could you send me this `text.html` file? I will check - what is the problem with it?

**Comment by monzug** [comment]
sure.

**Comment by irina060981** [comment]
Monika, I guess what could be a problem - I didn't test it with the local file - I tried right now and see - that it is reactivating on reload, but icon looks like as disabled and context menu doesn't work.
But double click on the word still works after reloading - I will check what is the problem with icon and menu.

**Comment by monzug** [comment]
Irina, Thanks. I will get back to you on this as I need more testing. these
are the two scenarios that I have to test: 1) new build installed with
different pages already open.  2) new build installed and then open new
pages.
to be tested in chrome and firefox - check if  webextension works after
installation and then on reload.

**Comment by balmas** [comment]
NB I have always seen problems with local files and installation. I haven't focused on it because I don't expect the browser to always behave properly with local files.

**Comment by irina060981** [comment]
I have already spent some time for investigating - it looses Active status  at some moment with the message from content-process. But it appears to be not such an easy issue - I could work on it next week.

**Comment by balmas** [comment]
@monzug if the only problem is with a local file, and with remotely served files it works fine, I'm inclined to let that go. Do you agree?

**Comment by monzug** [comment]
let me finish testing the scenarios as said above and get back to you. I am
ok if it's only local files.

**Comment by monzug** [comment]
tested on Firefox
1) installed build then open several sites (not local files)  webextension
works fine
2) have the same sites open, uninstall the build and clear data. reinstall
the build. click on activate, nothing happens. to have the lookup working I
need to reload the pages. after reloading, the info panel is also loading.

**Comment by monzug** [comment]
in Chrome, it works as in Firefox.
question: is it ok that I need to reload the page after installing a build,
to have the extension working?

**Comment by balmas** [comment]
The way it worked before is that after a build was installed, the page was triggered to reload itself. If that isn't happening, then something isn't quite right still. 
@irina060981 , the place to check is the handleOnInstalled handler in the background-process.js. It should be triggering an Alpheios_Reload event to the page, maybe the tab id is not correct here?

**Comment by irina060981** [comment]
Hello, Bridget and Monika!

I have made an investigation and the problem appears here:
```
browser.tabs.executeScript(t.id, {
    code: 'document.body.dispatchEvent(new Event("Alpheios_Test"))'
})
```
The content script stops to catch events after the extension was reloaded. (without any error).
Tab id is passing correctly and doesn't need any wondow id for that.
I tried to change the code to something that manipulate the style of the tab, makes reloading - everything ends with success (so there are no errors in permissions) .
I tried to execute dispatch in the content part (to check for syntax errors) - success.

So I could make only one conclusion - after the extension is reloaded and before it was reactivated manually (be reloading page) - it doesn't listen to events registered by the previous extension load and that's why there are no error with the code.

So I couldn't understand how it worked before. May be I am missing something?
I tried to find similiar cases but I couldn't.

**Comment by balmas** [comment]
I will take a look at this tomorrow.

**Comment by balmas** [comment]
Ah, interesting. It seems to me this works the way it should in Chrome (i.e. any page with Alpheios activated on it catches the event and reloads itself when the extension is updated). But it seems not to work right in Firefox.  Will continue investigating that.

**Comment by balmas** [comment]
this one has me stumped. It does seem that in Firefox, once the extension has been reloaded, all of the event handlers embedded in the document by the content script are lost. I am not sure there is much we can do about this, and it's pretty much an edge case that we can document.

@monzug if you agree, I think we can close this now.
