### ISSUE TITLE
Safari add version and build number to the Info screen

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#133]
We need to pull the version and build number from the Info.plist file and use it to populate the browserManifest object that is passed to the UIController constructor. 

We should override get browserManifest in ContentProcessSafari and have it return a manifest constructed from the data in the info.plist file. I would hope this is available from the safari object . Might take some investigation to figure out how to get ahold of it programmatically.

**Comment by balmas** [comment]
looking at @kirlat 's refactoring in #128 the above instructions aren't quite right.  With those changes, uiController will be initialized in content-safari, so I guess it's in handleStateRequest that you can construct the manifest

**Comment by kirlat** [comment]
Probably refactoring of content script might cause confusion as the code differs from the current master version significantly. If some changes are needed to be done to content script before the testing of `safari-app-front-i3` is complete, we could probably merge `safari-app-front-i3` to master sooner (any moment). We do not expect to release code from master soon, so probably it will be relatively safe to do that.

**Comment by balmas** [comment]
let's try to get it merged tomorrow after Irina has had a chance to do her review.

**Comment by kirlat** [comment]
I was actually thinking about getting rid of browser manifest as a constructor param as it seems to be application dependent (webextension only) and we envision UI controller as a universal cross-app solution. Instead of passing a whole browser manifest, we can pick up pieces of data we need from there and pass them as props of an `options` constructor parameters object: `{version: 'x.y.z'}`. It should probably be more universal this way. What do you think?

**Comment by balmas** [comment]
@kirlat do you mind just taking this one then so that you can implement as you suggest? Thanks!

**Comment by kirlat** [comment]
We have not decided on UI components data format yet, but I would really like to simplify that comparing to what we have now, if possible. Right now we, on my opinion, have too many config objects in too many places, That's is error prone, hard to manage and keep in sync.

We could probably have all setting data in a two-level structure. Two-level is probably enough to handle complex cases, and three-level would be too complex for things like initializing with defaults. So I was thinking about something like:
```
options {
  // App level data
  app: {
    name: 'value',
    version: 'value'
  },
  // Text query related data
  textQuery: {
    selector: 'value',
    data: 'value'
  }
}
```
We could mimic the same structure in constructor options object (to keep it understandable). So far it's using a flat structure, for simplicity, but we could use two-level structure there too.

With flat structure, that would make options object names like `appName` and `appVersion`, where `app` would designate the first level (that this is an app-level data) and `name` and `version` would be names of the props within this group.

Would it be fine like that? With this we could manage unlimited number of groups and props within groups and that all would stay, I hope, pretty manageable and understandable. What's your opinion on that?

**Comment by balmas** [comment]
I think this is ok. I would prefer a 2 level over a flat structure I think, because it's a less typo-prone. at some point we might want an object we can validate but we can do that if/when we really need it.

**Comment by kirlat** [comment]
I can start using two level for manifest data. We can match this nicely into Vuex modules. @irina060981, are you OK with using a two level approach for storing our state data as shown below?
```
options {
  // App level data
  app: {
    name: 'value',
    version: 'value'
  },
  // Text query related data
  textQuery: {
    selector: 'value',
    trigger: 'value'
  }
}
```

**Comment by kirlat** [comment]
Now as we can pass app name and version number via UIController options object easily, I'm wondering if we really would like to parse `info.plist` for that.

Our core code, that provides an Alpheios functionality, is 99% the same between webextension and Safari. The only different parts are the ones that are responsible for browser-controls user interactions, but that would not change often.

We could probably say that there will be a pretty close feature parity between webextension and Safari. Once we add a new feature to the core code, it will be available to both extension versions. That's except for browser-controls UI, of course, but that again would stay stable. Not very likely we will change this part too often.

So I'm thinking: what if we keep the same version between Safari and webextension? Once we add some new feature, it will be available on both platforms with pretty minimum effort. If, however, some UI features are not available in Safari, it will still be not available there for a long time (until Safari API would change), so that'll be a constant difference between Safari and webextension that will be carried on in time between extension versions).

On my opinion, the same version number will be highly beneficial to users. The number will reflect available functionality, and it would enable comparing versions of plugins across platforms.

For this, we could use version from manifest for both webextension and Safari. In Safari, we can read this file during transiplation, not runtime, by importing it into an app. Simple and effective. And we'll have a single source of truth for both platforms: a `manifest.json` file.

What do you think about that?

**Comment by kirlat** [comment]
As an alternative we could introduce two versions: a core version and a platform version. 

A core version would reflect available Alpheios functionality and will increase with each new build of components and its dependent libraries. A platform version would reflect changes in platform specific code (webextension, Safari, PWA, embedded lib). It would be always different across apps, as those apps would be on different state because of its platform-specific differences.

Users would probably be interested in a core version number as it will reflect functionality available to them. We can probable read it from `components` package.json. 

Platform specific version could be read from corresponding `package.json` files of the app packages (webextension, PWA, embedded lib). For Safari it probably has to be `info.plist`. In this case we would update app version numbers in app's `package.json`s only when we add some functionality to the platform-specific code of the apps, not when we rebuild them with the new version of `components` library.

**Comment by balmas** [comment]
I was thinking about this too, as I was trying to decide what the release version for the safari extension should be.

1. I agree keeping a consistent version for the webextension, whether it's a Safari build or the Firefox/Chrome is a good idea. Since the different platforms require that this be in different files (i.e. manifest.json for FF/Chrome and Info.plist for Safari) it would be ideal if our build process was responsible for incrementing it and updating those files.  

I think we can continue to use semantic versioning for this, but the build number is implemented differently across platforms. 

In the manifest.json for FF/Chrome we have a 4 component number which can have these parts major.minor.patch.build (and for the Beta release we are on 2.0.3.x)

In the Info.plist for Safari, the release number is a 3 component (major.minor.patch) in CFBundleShortVersionString and the build number is in CFBundleVersion (which itself can be 3 components but doesn't have to be).  

I have currently set the release number to 2.0.4 (x) for Safari but it should probably be bumped to 2.1.0 (x)/2.1.0.x for the release since the have been some fairly significant code changes needed in the webextension code to support it.

So we could have a separate file that keeps track of the release and build number and then have the build process increment the build number each time any build is run, and the release number upon request.  (How this should work with development builds in branches I'm not sure. It's a balance between how much effort to invest to wire something really foolproof up, versus just adhering to manual best practices that we define)

Whatever we do though should ideally be applied consistently across all application platforms (i.e. webextension, pwa, embed-lib) as well as the component libraries.

2. Core vs Platform vs Library versions
I think managing a single "core" version across the different dependent repositories could be a little unwieldy. I would like to be better about managing the versions of the different alpheios repositories and I think if we can automate this in the build process it will be a step in the right direction.

**Comment by irina060981** [comment]
I have read about the ability of changing Info.plist programatically - and it is not allowed, if I understood coorectly. Because all files in application folders could be changed only manually and have read-only permision for programatically changes.
Also If this way could be found - it could become a reason to reject to our extension from Apple team check.
I have read it here:
https://stackoverflow.com/questions/43433135/updating-value-in-info-plist-programmatically
https://stackoverflow.com/questions/12817272/editing-info-plist-possible-programmatically

**Comment by balmas** [comment]
Ah I was only suggesting that we change it at build time, not run time (i.e. by having a build script update the Info.plist files before creating the bundle. But since we don't actually *have* an automated build for Safari right now anyway, it might not be worth the effort at the moment.

**Comment by irina060981** [comment]
Bridget, I am really surprised with this Apple's approach - there is no normal automated build process with any easy update of Info.plist using some scripts.
And I was even embaraced with that phrase - that if you will find it - you would be punushed by Apple team on checking your extension. I just realized that I didn't ever find information what else could be reasons for rejection. 
I am a newbie In Apple development and it is really far from what I expected to see .

**Comment by kirlat** [comment]
What if we stick with the best practices and use Conventional Commits (https://www.conventionalcommits.org/en/v1.0.0-beta.2/) as a base of our versioning protocol? If we add a special tag into each commit (`fix:`, `feat:`), then, based on that, an automated tool like https://github.com/conventional-changelog/standard-version could bump a corresponding version number automatically. It supports Lifecycle Scripts (https://github.com/conventional-changelog/standard-version#lifecycle-scripts) that would allow us to hook our own scripts for specific tasks like increase a Safari version number or sync versions across different repos. 

The other advantage is that git commit messages will be standardized and it will be much easier to understand what was going on from the git log.

What do you think? Would sticking to those practices be beneficial to us?

**Comment by balmas** [comment]
I think generally, yes. I think all of this requires discipline and clear communication of the practices we have been and will be following. We haven't been using squash commits so that would be a change although i think this methodology doesn't absolutely require that .

Let's all think about it over the next couple of days and talk about this together in Monday's check-in and make some decisions then.

**Comment by kirlat** [comment]
In the latest version, 8450edb24a6bd6a48a1b48e35f371482897d4f27, we can specify Safari's App Extension version manually in a `content-safari.js` file. Maybe we can use this as an intermediary solution?

If that is acceptable, I can merge that into master as it will already be an improvement over what we have now in master and it will also introduce UIController updated that might benefit other apps. Then, when we'll decide on the exact versioning protocol, we could put that changes on top of the current version. What do you think?

**Comment by balmas** [comment]
do you mean just duplicating the version information that's in Info.plist in the content-safari.js where it calls the UIController constructor? I'm fine with that as an intermediate solution while we figure out how we want to handle versioning in a more automated way.

**Comment by kirlat** [comment]
Yes, so for now in `content-safari.js` we would have something like:
```
uiController = new UIController(state, {
      app: { name: 'Safari App Extension', version: '2.0.3.0' }
    })
```
Just from our previous experience with Apple we might not expect of any fast and easy solution in build automation. But with this, we'll already have something to show in an info panel. That's probably better than nothing.

**Comment by balmas** [comment]
Could we pull this version from the package.json file then, just like we do with the Chrome/FF version. If we commit to keeping that in sync with the version in the Info.plist even if we can't do it automatically just yet, that would be a step in the right direction.

**Comment by kirlat** [comment]
That's a great idea! Will implement that.

**Comment by balmas** [comment]
This can be tested in Build 2.1.0.5. 
 
@monzug it's not fully automated but the release/build number should now appear in the info screen for Safari too. We are incrementing the minor release version of the webextension with the Safari release, so this is build 5 of the 2.1.0 release.  It's a single code base for Safari and Chrome/FF.  We may or may not issue a 2.1.0 release of Chrome/FF at the same time. Will decide that later.

**Comment by monzug** [comment]
yes! it's there - Safari app Extension 2.1.0.5
