### ISSUE TITLE
add support for alpheios-ignore data attribute

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#15]
We need to be able to identify areas of a page on which the alpheios tools should always be deactivated. In v1 of the tools we used an alpheios-ignore class for this.  Should reimplement. 

3rd party site publishers can use this to control how Alpheios interacts with their site, and we can use it in our own components (e.g. the inflection tables and should be deactivated)

**Comment by kirlat** [comment]
I'm thinking that maybe a data attribute will be better for that, or we can program both for compatibility and stick with data attributes for all future works. My idea is that classes should be used for styling only  (since we have data attributes now) and data attributes should represent meta data (which this case is, I believe). What do you think?

**Comment by balmas** [comment]
Agree! Updating the title of the item accordingly.

**Comment by balmas** [comment]
moved to components repository.
