### ISSUE TITLE
Safari: not activate after page reload 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#162]
in Safari, if I reload the page in http://www.poesialatina.it/_ns/Greek/testi/Homerus/Ilias01.htm, the red icon is on but the webextension does not work (e.g. double click does not work).
same site in Chrome in Windows, on page reload the info panel (or any other tab in Options panel) is generated and webextension is on.
same in http://www.thelatinlibrary.com/lucretius/lucretius1.shtml  and   https://it.wikibooks.org/wiki/Greco_antico/Aggettivi_della_seconda_classe

**Comment by balmas** [comment]
assigning this to @kirlat to investigate. I suspect there must be something in the code of these pages that is causing the javascript to stop executing, although I'm surprised to see the Latin Library on the list of sites with problems because there is little to no javascript on on that site. It could be an HTML markup issue rather than Javascript specifically.

**Comment by kirlat** [comment]
This issue is specific not to any particular sites, but to every site, actually. This is related to idiosyncrasies of Safari app extension architecture.

This is how it works in webextension. In background script we have state objects that reflect a state of extension instance within each browser tab. Also, we have a callback in a background script that is triggered by a tab reload. Once we catch that, we know in what state extension was in a tab that was reloaded, and we can send a request to that tab that will restore extension to a state it was in previously.

Safari is a different story. Instead of a background script we have an app extension which is within a macOS environment, not within a browser one. Because of this, it does not receive any tab reload or other similar events (@irina060981, @balmas, please correct me if I'm wrong here). Thus, we cannot restore extension state on page reload. The only API I know of that can give access to some network info are network filters (https://developer.apple.com/documentation/networkextension/nefilterdataprovider) but I'm not sure they can track page reloads and it feels a little over the top for our task.

So the only way I can think of to make this work is to make a content script, when tab is reloaded, to inform extension background that the state was reset. A background will remove an active state icon after receiving such message. Thus, on every page reload an extension will be reset to an initial uninitialized state. Not perfect, but at least consistent.

What do you think about such solution? I implemented it in a `webext-i162` branch, and if we can accept such behavior, I can issue a PR.

**Comment by balmas** [comment]
If we can't catch the page reload event then I think your solution is fine.

**Comment by kirlat** [comment]
Merged into master

**Comment by balmas** [comment]
Please test in build 2.1.0.11

**Comment by monzug** [comment]
tested in build 2.1.0.11. on page reload, the tools are automatically deactivated

**Comment by balmas** [comment]
I think that was the only option in Safari. Passing to @kirlat to confirm.

**Comment by kirlat** [comment]
Yes, if there are several frames on the page and we cannot determine the one that will hold an activated script (that's the usual case), the only option we have is deactivate extension completely. That's without going too dip into hacking macOS app networking filters and stuff which we decided is better not to touch right now (if ever).

So the correct behavior on pages with multiple frames for Safari extension is to be deactivated and stay that way no matter what.

**Comment by kirlat** [comment]
Also, despite extension functionality being deactivated, an Alpheios icon can still be turned on and off. That's because there is no way for an app extension part (the one that controls the icon state) to know that a content script is disabled and because there is no way for the content script to tell an app extension part about it (without going into extreme complications, at least).

This might cause confusion to the end user. Probably we can display a message on a page saying that the extension is disabled, or maybe we can introduce a special message to the app extension part that will let know about extension being disabled, or maybe we can experiment with methods of finding out a single frame where we would activate an extension. However, this all be very time consuming and may not guarantee a positive result. Also, it's important to understand what percentage of sites are affected. Would we have an extension not working on half of the sites that are of interest to our users or would that be something of much lower percentage points? It all boils down to our priorities, I guess. @balmas, what do you think?

**Comment by kirlat** [comment]
While working on #170 I tried an approach that can allow us to disable icon and menu item on sites where extension will be disabled (i.e. with frames). This is how it works.

Once content script is loaded into a page with frames, it creates a state with `DISABLED` status and sends that to the Safari app extension. Once the app extension receives this message, it knows that a content script cannot be run within this specific tab. Then the extension disables a button and a menu item that activates an Alpheios content script so the script can never become active.

It worked well in my tests, but I don't have an extensive suite of test cases for that. So maybe I include it to the build and we'll give it a try? What do you think?

**Comment by balmas** [comment]
@kirlat a couple things:
1) I think this particular issue isn't actually specific to pages with frames. The original report was that on page reload of various pages, all without frames, the state was not being retained. In the FF/Chrome extension, the background process catches browser.webNavigation.onCompleted event, checks for the tab in its state object and uses the tab id to restore state accordingly.  In the Safari extension, it seemed that we didn't have access to such an event in the app extension so handling of page loads is done by catching DOMContentLoaded  in the content script, and resetting the state. But this meant that for Safari we couldn't retain state between page loads or page navigation.  That was the change you made in 84296dceca5330333893b6c2c955ec6a75d80659. So that would be causing the behavior Monica is seeing here. Upon a little further reading, I am wondering if we might be able to solve this better though in the `validateToolbarItem` method of the `SafariExtensionHandler.swift` class.  According to the very obscure Apple documentation (https://developer.apple.com/documentation/safariservices/sfsafariextensionhandling/1639492-validatetoolbaritem) this method is called whenever the browser state changes in such a way that might affect the toolbar item. We currently use it to respond to a click on the context menu (see #124) but maybe it is also invoked when the user navigates to a new page or reloads the page? and so maybe it could be used to send a message to the content script to recover its state?

2) Separate from that, since we do have to disable Alpheios in Safari on pages with frames, I agree generally with the approach you describe above, but wonder if we could just generalize the current handler for the Alpheios_Embedded_Response event, which effectively does the same thing for pages which have the alpheios embedded library loaded. In that case, the embedded library fires the Alpheios_Embedded_Response event which the content script catches and uses to deactivate the extension, retaining its state so that it can be automatically reactivated (if appropriate) on navigation to another page. I have no idea actually if that is working right now with the Safari extension, but it seems we need a more general way to notify the background that we want to deactivate Alpheios for the current page, while still retaining the previous state for the tab when new page is loaded.

**Comment by monzug** [comment]
@kirlat - this issue is reproducible in all sites that I tested: 
http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-100.html
http://www.poesialatina.it/_ns/Greek/testi/Homerus/Ilias01.htm
http://www.tradurreantico.it/latino/grammatica-latina/morfologia/verbo/possum-latino/
https://it.wikibooks.org/wiki/Greco_antico/Aggettivi_della_seconda_classe#Temi_in_liquida
http://penelope.uchicago.edu/Thayer/e/roman/home.html
http://thelatinlibrary.com/lucretius/lucretius2.shtml

**Comment by balmas** [comment]
please test in build 2.0.1.13

**Comment by monzug** [comment]
tested in few sites on safari build 2.1.0.13 - on reload with tools active, the functionality is still there
