### ISSUE TITLE
Safari: issues in build 2.1.0.9

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#166]
few issues that I have just noticed:
1) can't enlarge Option panel or Define panel and can't scroll down
2) problem activating the tools in Loeb Classics

to be retested in next build

**Comment by irina060981** [comment]
1) The problem with scroll and enlarge was the same as for incorrect panel width (inflection table messed up). Solved in https://github.com/alpheios-project/webextension/issues/135#issuecomment-440245480

2) problem activating the tools in Loeb Classics
@monzug , what do you mean here?

**Comment by irina060981** [comment]
https://github.com/alpheios-project/components/pull/285

**Comment by irina060981** [comment]
Monicf, I have similiar problems with http://www.poesialatina.it/ sometimes - but i haven't found any consistent pattern in it.
I think it comes from our way of exchanging activation status between browser and application.
It seems to me that it could be solved during future refactoring of states .
What do you think @kirlat ?

**Comment by monzug** [comment]
I just compare Loeb classics in chrome and safari. In safari again double clicking is not working, while in chrome it does. I have screenshots if needed. can't find reproducible steps, though. working on it...

**Comment by irina060981** [comment]
merged 
I didn't close it while investigation of activation problems is not ended

**Comment by kirlat** [comment]
It's hard for me to assume what the problem is without being able to reproduce it, but, as well as timing (although I haven't seen any timing issues in my tests), it might be a complex multi frame host page structure. The content script in Safari is loaded on every frame of the page because that's how it was architectured by Apple engineers. We don't need this behavior, so we're using a filter to sort undesired frames out. But maybe several frames would slip through the filter in some complex cases. This might, in theory, to cause some issues with activation. But that's just a wild guess ...

**Comment by monzug** [comment]
interesting. In this case, it would apply to all sites. Unfortunately my
experience is on a specific site (loeb classic). I will spend more time on
different site and see what happens. I thought it could be related to the
number of sites already opened on safari browser with alpheios activated,
but again could not find a reproducible scenario yet. Thanks

**Comment by monzug** [comment]
@kirlat, could it be that it's waiting for the option panel (or info panel) to be generated and it hangs there? let me explain, I just tested again the activation issue on latest build 2.1.0.10. what I noticed this time, tools are active and double click works on Loebclassics but as soon as I browse away from the main page to go to the authors section, the tools are still active (red icon is on) but double clicking does not work and the info (or option) panel does not pop up.

**Comment by monzug** [comment]
thanks. more complicated than I thought. I will have to do extensive
testing on different sites.

**Comment by balmas** [comment]
we may have to accept that Alpheios won't work properly on complex sites like this in Safari, at least not for the initial release of the Safari extension.

**Comment by monzug** [comment]
tested again in build 2.1.0.11 - confirmed that tools don't work on Loeb Classical Library, I mean they partially work but as soon as I browse the site, the Alpheios functionality is gone. @balmas, assign back to you to be consider for further releases

**Comment by balmas** [comment]
I believe the Loeb Classics site may actually be working now in build 2.1.0.12. Please retest. Thank you!

**Comment by monzug** [comment]
this works now. However we are still missing the pop-up when browsing through pages. In chrome the pop-up is generated every time I browse a new page.

**Comment by balmas** [comment]
I am not actually sure we *want* the popup to be generated everytime we browse a new page. A couple of questions:
1) do you mean the popup that you get when you select a word or the panel?
2) what should happen is that if you activate the tools, then browse to a new page, the panel status should be restored with each new page. So, for example, if the panel was open when you browsed to a new page, it should stay open. And if it was closed, it should stay closed (but the tools should stay activated if they were activated)

**Comment by balmas** [comment]
Ok, @kirlat this is interesting. The behavior seems to change depending upon *how* you navigate to a new page.  For example, if I have the panel open and then enter a new URL in the Safari location bar, the panel reopens after the new page loads. However, if I follow a link on the page to a new page, the panel status is not restored.

**Comment by balmas** [comment]
Actually, I think this is also an issue in Chrome too. For example, on http://www.poesialatina.it/, the navigation options are offered as menu options on the page. If you use those to navigate, first the panel and popup are closed (due to the clickaway) directive, then the navigation happens, so by the time the new page is loaded, the last status is that the panel was closed.  

I'm not really sure there is much we can do about this, short of dropping the clickaway behavior, but that was something @abrasax specifically asked for.  It's a question of which is more important -- clickaway closing the panel/popup or retaining state across pages which use in page links for navigation. I don't really know what the answer is.  Personally I don't like the clickaway directive because it closes the popup and panel when I don't want it to sometimes.

**Comment by monzug** [comment]
Plus users are used to see the panel so it's an expecting behavior.

**Comment by monzug** [comment]
see panel state issue #174
