### ISSUE TITLE
add auth polyfill for Firefox

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#202]
make the auth code work in the Firefox extension

**Comment by kirlat** [comment]
This works with the Mozilla's browser polyfill we're using right now. No special changes to the `auth0-chorme` are required.

The only problem is that authentication is taking 60+ seconds. This seems to be caused by a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1528562. A way to fix it is to change the pref **extensions.webextensions.identity.redirectDomain** to use **extensions.mozilla.org**, but that is not a kind of solution we need.

Hopefully, there will be some help from Mozilla's side in solving this.

**Comment by balmas** [comment]
If I understand the Firefox bug tracking system properly, this should be fixed in Firefox 68

**Comment by balmas** [comment]
or actually maybe the next Firefox release, 67. It has been approved for 67 beta 12

Closing this and setting to wailing_verification.

**Comment by monzug** [comment]
I have Firefox Quantum 66.0.4 (64-bit)  and it does take sometimes. we should test when the version with the fix is available.

**Comment by kirlat** [comment]
According to the FF release schedule (https://wiki.mozilla.org/Releases/Firefox_67), version 67 shall be available on May 14th, which is today. As it will probably be rolled out in stages, it can arrive any time from now.

**Comment by monzug** [comment]
I checked the Firefox page when testing the issue and it was not available
yet

**Comment by monzug** [comment]
Firefox 67 ships to the stable release tomorrow, May 21st

**Comment by monzug** [comment]
Tested in firefox 67.0.1 (64-bit) - authentication was superfast, both sign up and log in.

the fix to this issue is supposed to be released in 67 beta 12. will test again then but looks good to me

**Comment by monzug** [comment]
looks good to me - FF 68.0
