### ISSUE TITLE
Safari: login form changes

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#243]
A few cosmetic tweaks to the login form in the app: 

1. change "Please enter your credentials to log in" to "Login to save your wordlist."
2. Add a link below that text which says "User Account Tutorial" This should link to "https://alpheios.net/pages/tutorials#safari-user-account" (but please put this address in the separate env file that we have the api links in)

**Comment by kirlat** [comment]
We can't put a link to the UI of a macOS app because there is no visual element like that. We shall also follow the HID guidelines in creating our interface: https://developer.apple.com/design/human-interface-guidelines/macos/overview/themes/. Using the guidelines, the most appropriate control, on my opinion, will be a button. It executes an action: opens a help page in the browser window and I think that's what buttons are for.

If to put a button below the text, the UI would probably be unbalanced. Also, the text field on the left, where we're showing this message, is used for other messages too, and some of them can be quite lengthy (i.e. error messages), sprawling across multiple lines. That will push the button more to the bottom thus making it look even worse.

I'm thinking maybe if it would be nicer to put it to the right, next to the two other buttons that we are showing currently:
![image](https://user-images.githubusercontent.com/18631055/65601812-dcea6680-dfb3-11e9-978a-75c298549980.png)

The buttons clustered this way would look nicer, it seems to me. @balmas, what do you think?

**Comment by balmas** [comment]
yes, I agree. Thanks!

**Comment by balmas** [comment]
QA 3.0.1.72 (Safari build in Dropbox)

**Comment by monzug** [comment]
both changes are in.
