### ISSUE TITLE
Safari: password reset

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#245]
I just realized we didn't implement password reset in the Safari extension. Is this available in the Swift api? I tried to see how I could do it with the universal login form, but I don't see a way to do it :-(

**Comment by kirlat** [comment]
This shall be handled by the new Auth0 SPA SDK modal that has a password reset functionality.

**Comment by balmas** [comment]
@monzug please just verify password reset functionality on safari

**Comment by monzug** [comment]
functionality is there, however when I logged in after changing  the password, I got logged out immediately. the trick was to click on login again. same as issue #252

**Comment by balmas** [comment]
any thoughts @kirlat ?

**Comment by kirlat** [comment]
@monzug: This can be a timeout issue. Default timeout set by Auth0 is 60 seconds. If not to enter user credential fast enough, it will fail and steps of retrieving user info will be omitted. As a result, no user info will be shown and user status will be displayed as "logged out".

To verify if it is a timeout we can open a browser's console (in Safari we can right click on a page, select inspect, and in the dev panel opened select a console tab). In case of timeout it will have something like "Auth0 login request failed" with the error being "timeout".

There is a fix that is increasing timeout from 60 seconds to 5 minutes, it is merged into master, but has not been built into a Safari app extension yet.

**Comment by kirlat** [comment]
I've tested it with the code having an increased timeout and it worked well for me. I think that must be that. The whole workflow where the user opens the pop, selects "reset password", enters his or her email, waits for the email to arrive, clicks on the reset link, coming up with the password that was not used previously, (probably and hopefully) recording it somewhere and then entering into the form to log in requires the popup to being open for quite a while. If timeout is short enough, that will most likely trigger an error as the popup will be opened for longer than the timeout duration is. 

I'm not even sure if 5 mins is enough for an average user. I was prepared for what will come onto me, but an average user might not check an email immediately, the email may not be delivered to the user's mailbox right after the message arrived to the server, the user might have difficulties with creating a new password and/or recording it and so on. So we might even set it for longer. Or we might not bother much about this scenario because probably this functionality won't be used that often and clicking on the login button one more time is probably not a big deal (or maybe it is). @balmas, @monzug what do you think?

**Comment by balmas** [comment]
I think we could go up to 10 minutes but also agree it's an edge case.

**Comment by monzug** [comment]
agree that 5 minutes should be ok

**Comment by balmas** [comment]
QA-3.0.1.80 is in Dropbox

**Comment by monzug** [comment]
it worked 2 out of 3 times (the first time I still got the log in page, see screenshot below).
Also, when I hover over Don't remember your password, I see a Run script message, see below

![Screen Shot 2019-10-15 at 2 21 03 PM](https://user-images.githubusercontent.com/41396793/66832324-fd299780-ef59-11e9-80d0-61c2c58929eb.png)

![Screen Shot 2019-10-15 at 2 26 35 PM](https://user-images.githubusercontent.com/41396793/66832349-061a6900-ef5a-11e9-8a08-89534956ba15.png)

**Comment by monzug** [comment]
just got it again
![Screen Shot 2019-10-15 at 2 47 30 PM](https://user-images.githubusercontent.com/41396793/66832759-d881ef80-ef5a-11e9-8734-59c95226be24.png)

**Comment by balmas** [comment]
the run script notice is something with the form itself. I've make that a new issue #259

**Comment by monzug** [comment]
it does not happen in Chrome, only Safari

**Comment by balmas** [comment]
hah, you were reading my mind :-)

**Comment by balmas** [comment]
@monzug I am tempted to let this one go as-is. What do you think?

**Comment by monzug** [comment]
FAQ? let me try one more time a reset psw

**Comment by monzug** [comment]
and it worked! ok, we can move away from this one...
