### ISSUE TITLE
upgrade auth0-spa

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#266]
something in between auth0-spa release 1.3.2 and 1.5.0 broke our Safari authentication. Need to investigate and upgrade.

**Comment by balmas** [comment]
I'm not sure what the latest version of auth0-spa is but we should try to upgrade to whatever that is

**Comment by kirlat** [comment]
This has been handled by the #284. Auth0 SPA is updated there to the latest version at the moment, 1.8.1.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200513448

Requires Authentication regressions in Safari App Extensions

**Comment by monzug** [comment]
I signed in with google and now I cannot log out both from latin library and loeb classics. I keep clicking on log out button from User Account tab and nothing happens.

![Screen Shot 2020-05-22 at 4 56 57 PM](https://user-images.githubusercontent.com/41396793/82681084-88d07880-9c4d-11ea-84c3-ac266470790e.png)

**Comment by kirlat** [comment]
I've tried to reproduce it on Safari, but I was not able to. I was testing it on both Loeb Classics and The Latin Library, was trying different scenarios, but no matter what, the logut worked for me as expected. My platform was Safari 13.1 (15609.1.20.111.8) and macOS 10.15.4.

The only issues I've encountered is the login popup loaded partially (see the screenshot below):
![image](https://user-images.githubusercontent.com/18631055/83139520-924e5a80-a0fd-11ea-916c-c6a2a05e1e9d.png)
The happened on a couple of occasions, it seems to be a subject of network conditions. If to right click on the popup and reload its content, it worked without a hitch after that.

The other issue was that if to leave a page with a panel opened for a few minutes and do nothing there, it might go to some kind of sleep, or so it seems. Like if Safari unloaded part of the extension to save memory, energy, or something of that kind. If, after a while, return to Safari window with an extension, it feels like an extension's UI is frozen: one can move a mouse pointer over a screen, but it does not react exactly as it should. For example, if we hover over a button, a pointer should change itself to a hand, but it doesn't. It still is represented by an arrow. Feels like a CSS code responsible for its appearance was deactivated. Then, after a click or two somewhere, it all returns to normal, as if those missing parts are loaded and put into action. I don't know, but maybe a sticking logout button is caused by something like this? I did not experience it, but maybe different systems behaves not the same way exactly?

**Comment by balmas** [comment]
> I signed in with google and now I cannot log out both from latin library and loeb classics. I keep clicking on log out button from User Account tab and nothing happens.
> 
> ![Screen Shot 2020-05-22 at 4 56 57 PM](https://user-images.githubusercontent.com/41396793/82681084-88d07880-9c4d-11ea-84c3-ac266470790e.png)

@monzug if you can still reproduce this, can you try closing and reopening the panel and clicking logout again? I have noticed occasional non responsive buttons in the UI (in Chrome), for example, sometimes when I click on Lookup in the lookup box, rather than pressing return, it does nothing, and then the next lookup it works fine.

**Comment by monzug** [comment]
Not able to reproduce the logout problem described in the above scenario in Safari App Extension 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404

@Balmas, I have a question: when I sign in with Google in Safari, it does not prompt for id/psw. I am logged in automatically, and I waited for more than 2 minutes too. In Chrome (Mac/PC), it does prompt for id/psw initially, then in any subsequent attempt, I select the user and then I am automatically logged in. why in Safari I do not get the prompt for id? even if I chose to save id/psw automatically, shouldn't it prompt for which user I want to log in with? what if I want to login as a different user?

**Comment by balmas** [comment]
> @balmas, I have a question: when I sign in with Google in Safari, it does not prompt for id/psw. I am logged in automatically, and I waited for more than 2 minutes too. In Chrome (Mac/PC), it does prompt for id/psw initially, then in any subsequent attempt, I select the user and then I am automatically logged in. why in Safari I do not get the prompt for id? even if I chose to save id/psw automatically, shouldn't it prompt for which user I want to log in with? what if I want to login as a different user?

Yes it should. I think we may need to just tweak a setting in the Safari Login configuration for this.  I'll convert this to a new issue.

**Comment by monzug** [comment]
ah, ok. glad you know how to fix it.
