### ISSUE TITLE
prevent page styles from affecting the alpheios vue component styles

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#29]
We probably need to be explicit about as much as possible in the styles on the parent elements. 
issues noticed so far:
- some of the css for the vue components (such as the uikit buttons) use relative font-sizes and it results in the button text on the popup being really small (e.g. try on http://texts.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg005.alpheios-text-grc1/passage/1-30)
- text direction in the page (affects css pseudo styles such as :after - see the popup when used with persian on http://ganjoor.net/hafez/ghazal/sh1/  - the ; shows up to the left of part of speech in the popup instead of to the right)

**Comment by kirlat** [comment]
UIKit uses rem sizing for many of its text elements. rem sizes are related to a font size of a page root element, `html`. 

There are two types of scaling in modern browsers:
* zoom (the most widely used one). It scales everything proportionally, no matter what units are used: pixels, ems, rems. For such zooming, a choice of size units does not make any difference.
* default font size zooming. These setting that are usually hidden within browser panels allow user to change a base font size. With this type of zooming, elements with sizes set in ems and rems will scale and px-based sizes will stay the same. To support this style of zooming, and to provide accessibility in a browser, it is important to use relative units for sizing.

However, some sites and framework, such as Bootstrap 3, explicitly sets a font size of `html`. This effectively kills any font-based zooming. It also causes problems with our panel as it adjusts sizes of it's elements.

We cannot fight back and override `html` font setting because it will change a page appearance.

Trying to keep panel scalable, we can switch to ems. The problem with ems, however, is cascading, so two nested `text-small` elements would produce a font that is smaller than the one within a single `text-small`. It will be very inconsistent. It also will not be able to zoom according to the browser font settings because it will be related to the root of our styling classes, `auk`, not to the `html` font size.

So I think the only way to fix this is to switch into pixels. We'll lose an ability for a font-based zooming on sites that do not override `html` font size, but we'll guarantee a consistent appearance across all websites no matter what their styles are. Using pixels seems to be the only available solution for us.

What do you think? Are there any other alternatives?

**Comment by kirlat** [comment]
Text direction should be fixed with 7b1499b5b686c72d698b47d3090fc654975f5669.

**Comment by balmas** [comment]
Thank you for this analysis! I think you're right that to be foolproof with other pages we have to used fixed pixel sizes. It may be that we have 2 base stylesheets for the vue components - one for use in the extensions where we can't control base page styles, and one for use in libraries where we can.

**Comment by kirlat** [comment]
I like the idea with two stylesheets. Will try to create a solutions that will work reliable on different pages.

**Comment by balmas** [comment]
will enter a separate issue for the 2 style sheet build. This will probably be part of a separate project to externalize and distribute the vue components though.
