### ISSUE TITLE
Add language to ui

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#30]
Not sure exactly where/how to do this, but we should show the user the language the tools identified for a word selection so that errors due to language mismatch are easier to identify.

**Comment by kirlat** [comment]
I think this is a great idea

**Comment by balmas** [comment]
per discussion today, we may need to experiment a bit with what works best here. Something unobtrusive when we get results, versus something a little more obvious when we don't get results. I.e. if everything is working, they don't really need to see what language is chosen because it will be the right one, but if we don't get results, it should be more prominent and give them an easy way to change it.

**Comment by balmas** [comment]
@kirlat I love the popup header and footer. I also really like the display of the selected text and language at the bottom of the panel and the popup. (I did include a small fix to handle the change event in the popup in #40).

 I'm a little unsure about the message that offers the user the option to change the language. In order for this to work right I think we will need to do a few things:
1. If the user chooses to change the language here, we should probably rerun the query immediately
2. We need to have a page state override and this widget would actually control that, not the preferred default language. And then we have to apply that to the future queries for the page. Because we pull the language from the page itself, and if we are able to find one, we will keep overriding the default selection with that.

But I think for the alpha, it's probably okay as is, except that since we also show the language in the footer message, I think I'd like to only show the change language message in the header if we are don't have any lexemes which have definitions. What do you think?

**Comment by kirlat** [comment]
The idea with this language selector was that it would allow us to override language settings for any particular word (text selection). Then this language setting for each word (text selection) would be remembered and used for subsequent queries with the same text.

Thus, we would have three levels of language settings (in order of preference):
1. Language setting override set by user using a per-word language setting.
2. Language setting for a word set within an HTML code of a page.
3. Default language settings set in user preferences (probably that should be remembered and stored for each particular site or each particular page).

So if a lexical query returns no results, or we think that results returned are somehow incorrect, we offer user to change a language for that particular word. Choosing a different language would rerun a query. Then we could remember a language setting for each particular word.

I'm not sure what kind of granularity in setting a language should we offer. Would providing a setting for each word and a setting for each page, or site, be a good choice? What do you think?

Right now changing language for a word does not rerun a query nor does it gets stored anywhere. The purpose was just to show what kind of UI we could have. That's why it's shown for every query. I agree that it would be better to show it only for those queries that return zero lexemes.

**Comment by balmas** [comment]
Yes, that all makes sense. I am not sure either what level of granularity to offer here. For example, if we are going to remember per word per page choices, it probably makes sense to just remember the full results for that word and page, rather than only the language chosen. 

This is definitely something we need user feedback on. For the immediate term (i.e. the alpha release), I would say we should show the warning only if there are no morphology-service provided lexemes (we need to distinguish between these and the pseudo-lexeme we now create for the form).  We could probably check that quickly by looking for the provider property. Or more deeply by looking to see if any features were defined on the lexeme (above I said definitions, but I think features are actually a better test here). If we can just have the selection stored as the default language preference for the alpha (the change I made yesterday) I would also be okay with that. We can then ask for feedback and refine the behavior accordingly.  An added bonus for the alpha would be rerunning the query but I could live without it.

**Comment by kirlat** [comment]
Sounds like a great plan, will work on that.

**Comment by balmas** [comment]
closing this. Further work to be carried forward post-alpha via #43
