### ISSUE TITLE
Lexical data is loading from wordlist 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#330]
related to #328 ?
in latest build  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211118345
Alpheios Components 3.3.3-incr-3.4.x.20211116233 build i662-lexical-dicts.20211118457  in FF/PC.
Have wordlist with latin words saved in both Greek and Latin language. When I double click on a latin word from wordlist (e.g. legatione), that it has been saved in the Greek list of words, it keeps loading the message: the lexical data is loading in the pop-up. I have to close the pop-up.
No errors in the log.

![legatione](https://user-images.githubusercontent.com/41396793/142441445-e1b0e3b0-23d1-4292-95ee-2b5c9dec510d.JPG)

![page-language-greek](https://user-images.githubusercontent.com/41396793/142439634-a6be1846-9b36-4dff-bbb5-b88670ec34d6.JPG)

**Comment by irina060981** [comment]
No, I don't think that it is related to that errors .
But we have some problems with hanging lexical loading.

I saw it before simultaneously.
Will check.

**Comment by irina060981** [comment]
The problem is bigger.
When you select a word from the page (in Firefox) it does two requests - with defined language and with page language.
And adds two words with different language to the wordlist.
You could see them as almost empty line in wordlist.

And when you try to click on them from wordlist - they could not be loaded, because - they don't have homonym.
One copy with correct language has homonym and easily retrieved, the other with incorrect language - has no homonym and could not be retrieved.

And the most strange - it is reproduced only in Firefox (in my tests).

Need more time for investigation

**Comment by monzug** [comment]
uhm, not so happy to hear this. good luck digging into this issue...

**Comment by irina060981** [comment]
I rechecked - it is reproduced in Chrome too.
Easy steps:
- open any latin text (I use http://www.thelatinlibrary.com/livy/liv.21.shtml)
- set page Language as Greek 
- double click on any word - 2 words would be added to wordlist (to lat and grc)

**Comment by irina060981** [comment]
Bug is fixed.
New Release  is published.

**Comment by monzug** [comment]
this is fixed in  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211122338
Alpheios Components 3.3.3-incr-3.4.x.20211118338 build i330-loading-wordlist.20211122620 
now I am getting the following:
![Screen Shot 2021-11-22 at 2 42 48 PM](https://user-images.githubusercontent.com/41396793/142872005-7aaabcf5-c15b-4cc7-acf8-d92586e638f4.png)
