### ISSUE TITLE
two clicks to set Reset all in Options

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#333]
tested in FF/Mac in  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211122338
Alpheios Components 3.3.3-incr-3.4.x.20211118338 build i330-loading-wordlist.20211122620 
there is still something not quite right with settings in Options. so, I wanted to change lexicon (short definitions) in latin, so I unchecked Whitaker to add Paideia, but it would not change the glossary, so I deselected all. if I click on reset all once, it shows the lexicon field with Pick me. only when I click a second time, reset all does work.
this is in latin library and Scaife. 
![Screen Shot 2021-11-22 at 3 16 57 PM](https://user-images.githubusercontent.com/41396793/142877092-29335943-5250-4421-99bd-e0305750babe.png)
I tested an other site: https://www.tradurreantico.it/latino/grammatica-latina/morfologia/verbo/verbo-eo-latino/ 
and there is definitely something funny when changing glossary or when clicking on reset all. No errors in log. this is in FF/Mac.

**Comment by irina060981** [comment]
I could see the same in Chrome - so it is not browser dependent

**Comment by irina060981** [comment]
I have do some changes and won't be able to reproduce.
The bug was the following: 
- when a user clicks - Reset all - it uploads data from storage and update on the screen
but there was not defined a cleary query

Previously (I believe) uploading was quick and it was always uploaded before the next step.
But it seems to me that Internet becomes slower or our sources - in the described case the first step was too slowly.

I defined the order of these steps in the code.
Now it works fine for me
Waiting for your tests

**Comment by monzug** [comment]
this works now in build  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211123265
Alpheios Components 3.3.3-incr-3.4.x.20211123114 build i333-options-reset.20211123556
