### ISSUE TITLE
resize panel to show full inflection view

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#45]
when the user clicks on Inflect from the popup, the view should resize itself to show the entire table if possible.  The version of the table with empty columns and only matching columns is the default now and that's what we want to try to expand the panel to show the entirety of.

**Comment by kirlat** [comment]
The latest commit ae8fcf4f108f4b9b3e48851f2db95a112e581563 addresses this issue. If the panel is not wide enough to fit an inflection table fully, it will expand, but no more than a viewport width.

Since calculation of a table width can be done only when a table and all its parents are visible (otherwise it will be zero), the Panel (which controls an Inflection component visibility when tabs are switched) notifies an Inflection component when it becomes visible, so that an Inflection component will be able to calculate a table width. A width is then passed to the Panel which, in turn, adjusts its own width to fit a table fully, if possible.

I've tried to keep an Inflection component and a Panel as decoupled as possible. That's why design is generic, and requires a little bit more code. However, this can be important if components will be used separately.

**Comment by balmas** [comment]
this looks great. Thank you!
