### ISSUE TITLE
encapsulate business logic around selection of text

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#5]
There is a bunch of business logic around selection of text that should be encapsulated for reuse. An initial rough draft of this ported from the old Alpheios code can be found at https://github.com/alpheios-project/wordsvc/blob/master/src/source_selection.js

We probably also should consider an implementation that is compatible with the W3C annotation model's selector paradigms, in particular TextQuoteSelector.
```
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno23",
  "type": "Annotation",
  "body": "http://example.org/comment1",
  "target": {
    "source": "http://example.org/page1",
    "selector": {
      "type": "TextQuoteSelector",
      "exact": "anotation",
      "prefix": "this is an ",
      "suffix": " that has some"
    }
  }
}
```
(see https://www.w3.org/TR/annotation-model/#selectors)

I'm not sure where this class actually should go -- I don't think it really belongs in the data models library, and it may not be entirely possible to have a general purpose module for this, but the concepts at least need to be supported by whatever applications interact with user selection of text for processing from an html page.  

Some basic functionality that is needed:

1. automatic identification of language of the selected text, when possible
https://github.com/alpheios-project/wordsvc/blob/master/src/source_selection.js#L5-L23 provides an example of traversing the page to look for the closest specification of the `@lang` or `@xml:lang`. This is the minimum we could do, but it will only work where page authors have explicitly declared the language of the text. Other things we can do are examine the character set -- this will work okay for some languages, such as Greek, Arabic and Persian, less well for Latin.  We should always fall back to a default language which the user can specify upon initial activation of the Alpheios functionality.

2. retention of the surrounding context of the selected word
We will want to be able to encapsulate some information about the surrounding context of a selected word, for a number of different reasons. Some parsers and languages may require this for processing. In order to offer the user other relevant resources, information we can glean from the page may also be important (e.g. if the page identifies the text the user is reading using a standard identifier, we could query linked data sets for relevant annotations, etc);   This is where the W3C model makes alot of sense to reuse.

3. algorithms for identification of distinct words from within a user selection event
The browsers are much better at this than they used to be with the advent of the Web Selection API so it's not clear how much of the old Alpheios business logic around this is needed, but we previously had quite a bit of logic around identifying distinct words from within a user selection. This was maybe more necessary for use of the mousemove event which we really needed for character-based languages like chinese for which the doubleclick action didn't work well, but there was also a need for special handling of text embedded in SVG elements, punctuation, etc.  I think we should at least have a place holder for this which wraps the getSelection API, even if initially all we do is return what that provides us.
Started working on this at https://github.com/alpheios-project/wordsvc/blob/master/src/source_selection.js#L89-L164

4. Delegation to the LanguageModel for normalization of text
There will be normalization methods specific to individual languages that are implemented in the LanguageModel derived classes that we need to call on when processing a user selection.  Conversion to a standard unicode combination method, stripping of accents, etc.

**Comment by kirlat** [comment]
Thanks for listing important pieces that are required for the implementation. I'm also thinking that a use of W3C annotation selectors is a great idea.

I think those functions listed should be grouped by their domain. And probably it would make sense to have them even more granular. Language detection, on my opinion, consists of two related parts: HTML document parsing to find any language-related marks in a document and, if this failed, language guessing or language determination based on the text content. 

Document parsing is probably a format-specific thing, as we operate with DOM and DOM concepts is HTML-related. If we would parse a PDF document (don't know if we'll ever need that), we would do it differently. 

Language guessing, on the other hand, lies within a language specific domain, on my opinion. It requires some knowledge of the language itself, and knowledge of different languages to be able to make an educated guess. Some language detection algorithms uses n-grams which are characteristics of a language. Thus, it should probably belong to the language model.

Retention of surrounding context is probably format-specific too, because the selector itself depends on the media. 

Identification of distinct words probably belongs to a language model and should be part of it if we're talking about a language-specific logic here. But there probably should be a separate function that will deal with a format-specific aspect of it: determining node boundaries, selection structure, etc. So maybe it's better to split in two?

Normalization is clearly a part of language model, I think.

So looking at that, I can see two distinct domains: one that deals with language data and language understanding (should probably be within a language model) and the second one that deals with media format and its parsing (i.e. HTML, PDF, etc.). So I'm thinking maybe we could have some concept of media adapters that will abstract media we're working with from the language logic? This way we would be able to add support for a new media (PDF, eBook, so on) by just adding a specific adapter. What do you think?

Language detection is a very interesting problems. I've checked some services that are using AI for that and they were providing some consistent results in those little tests I've made. I think AI is probably the future of language studies and we should not miss it, but that would be out of domain for the current project.

**Comment by balmas** [comment]
Taking advantage of AI is definitely on our roadmap.

Agree that separation of language data and media format makes sense.

**Comment by balmas** [comment]
Notes from Slack:

I'm not sure it's at all helpful to you at this stage, but the code I was thinking about related to the Text Selectors is here: https://github.com/perseids-project/plokamos/blob/master/src/lib/models/ontologies/OA.js
it created a graph that corresponded to the open annotation data model, the precursor to the w3c model
on the selection side, it looks like we used a model from the dom-anchor-text-quote libary, see here https://github.com/perseids-project/plokamos/blob/master/src/lib/controllers/applicator.js
the library is here https://www.npmjs.com/package/dom-anchor-text-quote

(The developer for this library is one that is developing the Hypothes.is annotation tool)
It would probably be worth a little time to evaluate if it would be useful to use this library to support our TextSelector object
(I will add these notes into the issue to try to stick to our practice of documenting conversations in github...)

**Comment by balmas** [comment]
re point 3 in the list of functional requirements (algorithms for identification of distinct words from within a user selection event):

There is still a need for this. An example html fragment which illustrates one problem:

```
<p><span>Ambiguum</span>,<span>Clymene</span>,<span>precibus</span><span>Phaethontisanira</span></p>
```

In this markup words are identified by spans and css is used to add spaces between them for display. The browser automatically selects all words in the `<p/>` tag when an individual `<span/>` is clicked on, trying to be smart about parsing text.   This is not the desired behavior. One way we dealt with this before   on pages we published was to use custom classes to allow for an override of the browser selection algorithm (e.g. so `<span class="alpheios-enabled-word">`). This only works for pages we control, or that the publishers are willing to change, but that might be sufficient for this particular use case until we find otherwise.

**Comment by balmas** [comment]
additional notes on this: browser handling of getSelection on markup like this
```
<p><span>Ambiguum</span>,<span>Clymene</span>,<span>precibus</span><span>Phaethontisanira</span></p>
```
is a little flaky, at least in Chrome.
if you click on Phaethontisanira, it sents the anchor node as precibus and focus as Phaethontisanira. Same is true if you click on precibus. This makes it hard to use getSelection reliably with this sort of markup.

**Comment by balmas** [comment]
I'm closing this for now. We can open new items for specific improvements to the selection business logic as needs surface.
