### ISSUE TITLE
popup positioning and sizing issues

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#73]
I think the requirements we want to work with are these:

1. Popup should be positioned near the screenX and screenY of the mouse event
2. The bottom of the popup should not be below the viewport
3. The top of the popup should not be above the viewport
4. Minimum size but it should not be larger than the amount of space needed for the header and buttons and a small amount for the text itself. We want the popup to shrink to collapse unnecessary space.
5. Popup should flex both directions (rows and columns) to fit content 
6. But Need a max height and width that doesn't exceed some percentage of the viewport (there are a few very long persian definitions that could easily do this, e.g. try with  خون )

**Comment by balmas** [comment]
Alternative to max height, which might require too much scrolling for Arabic, is to move the buttons to the top of the popup and not worry about positioning fully within the airport. This is what we did in V1 and what @abrasax is advocating for.

**Comment by kirlat** [comment]
I think it won't look good if a popup will overflow a viewport. I want to try to make it work without that, and leave an overflow options as a last resort, if you don't mind.

The question about priorities: if a definition is long enough, and we have to increase a popup significantly to accommodate it, would we want to keep a popup near a selection (do not overlap a selection with a popup) and have it smaller, or would we rather want to increase a popup in size so that it will have plenty of space to show a definition but will overlap a selection? What's more important: not covering the selected word or having more space for a definition in a popup?

**Comment by balmas** [comment]
My vote would be for having more space.to show the definition. Not sure if @abrasax agrees.

**Comment by abrasax** [comment]
Are we talking about vertical or horizontal space? I care a lot less about
whether the selected word is covered or not than that the ratio of
horizontal and vertical be as appropriate as possible for the text being
displayed.

**Comment by balmas** [comment]
Still some instances of too much whitespace going below the fold. Not sure what causes this. Can address post alpha if need be.

<img width="816" alt="screen shot 2018-02-08 at 5 15 32 pm" src="https://user-images.githubusercontent.com/644870/36027824-d7f68bf8-0d6a-11e8-83fc-3ea920dce239.png">

**Comment by balmas** [comment]
closing. will open new issues for specific problems with popup size and position.
